project:
  type: website

  preview: 
    port: 5555
    browser: true
    watch-inputs: true
    navigate: true

  render:
    - "*.qmd"
    - "*.md"
    - "!etc/"

  resources:
    - "files/**"
    - "etc/**"

    # Things that need to be at the site root
    - ".htaccess"
    - "LiveSearchSiteAuth.xml"
    - "keybase.txt"
    - "y_key_31e0c4105fc75710.html"
    - "pgp_ath.asc.txt"

freeze: true

bibliography: files/bib/references.bib
csl: files/bib/chicago-author-date.csl

# Metadata stuff
pagetitle: "{{< meta title >}} | Nicole Von Possel"
author-meta: "Nicole Von Possel"

website:
  title: "Nicole Von Possel"
  description: "Nicole Von Possel is a PhD student at the Max Planck Insitute for Marine Microbiology."
  favicon: "/files/favicon-512.png"
  site-url: "https://nicolevonpossel.github.io/academic"
  repo-url: "https://github.com/nicolevonpossel/academic"

  google-analytics: "UA-527449-5"

  twitter-card: 
    image: "/files/profiles/twitter-card-large.png"
    card-style: summary_large_image
    creator: "@nicolevonpossel"
    site: "@nicolevonpossel"

  open-graph: 
    image: "/files/profiles/twitter-card-large.png"
    locale: en_US
  
  navbar:
    pinned: true

    left:
      - text: "About"
        href: "index.qmd"
      - text: "Blog"
        file: blog/index.qmd
      - text: "Publications"
        file: publication/index.qmd
      - text: "CV"
        href: "cv/index.qmd"
      - text: "Leisure"
        href: "leisure/index.qmd"
        
    right:
      - text: "{{< iconify bi envelope size=1.1em title='E-mail' >}}"
        href: "mailto:npossel@mpi-bremen.de"      
      - text: "{{< iconify bi maxplanckgesselschaft size=1.1em title='MPI' >}}"
        href:  https://www.mpi-bremen.de/en/Nicole-Von-Possel.html
      - text: "{{< iconify fa6-brands bluesky size=1.1em title='Bluesky' >}}"
        href: https://bsky.app/profile/nicolevonpossel.bsky.social
        rel: me
      - text: "{{< iconify bi github size=1.1em title='GitHub' >}}"
        href: https://github.com/nicolevonpossel
        rel: me
      - text: "{{< iconify bi linkedin size=1.1em title='LinkedIn' >}}"
        href: https://www.linkedin.com/in/nbvonpossel/
        rel: me
      - text: "{{< iconify bi googlescholar size=1.1em title='GoogleScholar' >}}"
        href: https://scholar.google.com/citations?user=DERzP-UAAAAJ&hl=en
  
  page-footer:
    left: |
      <span class="faux-block">{{< fa brands creative-commons >}} {{< var years >}} Nicole Von Possel</span>
      <span class="faux-block">All content licensed under<br>[{{< fa brands creative-commons >}} {{< fa brands creative-commons-by >}} Creative Commons CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)</span>      
    center: |
      <span class="faux-block">{{< fa brands orcid >}} <strong>ORCID</strong> [{{< var orcid >}}](https://orcid.org/{{< var orcid >}})</span>
      <span class="faux-block">{{< fa key >}} [PGP public key]({{< var pgp.key >}}) &emsp; {{< fa fingerprint >}} Fingerprint:</strong><br><span class="fingerprint">{{< var pgp.fingerprint >}}</span></span>
    right: |
      <span class="faux-block">Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)</span>
      <span class="faux-block">[View the source at {{< fa brands github >}} GitHub]({{< var github-url >}})</span>

format:
  html:
    theme: 
      - html/ath.scss
    grid: 
      body-width: 900px
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
    highlight-style: monokai
